import csv
import os
import pickle

import networkx as nx
from jptest import *

# Vorbereitungen
imports = '''
    import networkx as nx
    from networkx import community, clique
    
    import pickle
'''
load_graph = '''
    with open('graph.pickle', 'rb') as file:
        G = pickle.load(file)
'''


@JPPreRun
def pre():
    # read data
    G = nx.Graph()

    with open('movie_graph.csv', 'r') as file:
        reader = csv.reader(file)
        for source, target in reader:
            if source in mapping and target in mapping:
                G.add_edge(source, target)

    # store pickled
    with open('graph.pickle', 'wb') as file:
        pickle.dump(G, file)


@JPPostRun
def post():
    if os.path.exists('graph.pickle'):
        os.remove('graph.pickle')


# Aufgabe 1
@JPTest('Aufgabe 1', max_score=1, execute=[imports, ('task-1',)], timeout=300)
def aufgabe1(tb: JPTestBook):
    result = tb.get('G')
    test = tb.inject('''
        G = nx.read_edgelist('movie_graph.csv', data=False, delimiter=',')
    ''', 'G')

    yield tb.ref('nx').is_isomorphic(test, result), 1


# Aufgabe 2.1
@JPTest('Aufgabe 2.1', max_score=1, execute=[imports, load_graph, ('task-2-1',)])
def aufgabe2_1(tb: JPTestBook):
    result = tb.get('density')

    tb.inject(load_graph)
    test = tb.inject('''
        density = nx.density(G)
    ''', 'density')

    yield abs(test - result) < 1e-6, 1


# Aufgabe 2.2
@JPTest('Aufgabe 2.2', max_score=1, execute=[imports, load_graph, ('task-2-2',)])
def aufgabe2_2(tb: JPTestBook):
    yield tb.ref('cc') is False, 1


# Aufgabe 2.3
@JPTest('Aufgabe 2.3', max_score=1, execute=[imports, load_graph, ('task-2-3',)])
def aufgabe2_3(tb: JPTestBook):
    result = tb.get('shortest_path')

    tb.inject(load_graph)
    test = tb.inject('''
        shortest_path = nx.shortest_path(G,
                                         source='Mickey Mouse',
                                         target='Star Wars: Episode III - Revenge of the Sith')
    ''', 'shortest_path')

    yield test == result, 1


# Aufgabe 2.4
@JPTest('Aufgabe 2.4', max_score=1, execute=[imports, load_graph, ('task-2-4',)])
def aufgabe2_4(tb: JPTestBook):
    result = tb.get('max_degree_node')

    tb.inject(load_graph)
    test = tb.inject('''
        max_degree_node, degree = max(nx.degree(G), key=lambda x: x[1])
    ''', 'max_degree_node')

    yield test == result, 1


# Aufgabe 2.5
@JPTest('Aufgabe 2.5', max_score=1, execute=[imports, load_graph, ('task-2-5',)])
def aufgabe2_5(tb: JPTestBook):
    result = tb.get('max_pagerank_node')

    tb.inject(load_graph)
    test = tb.inject('''
        max_pagerank_node, pagerank = max(nx.pagerank(G).items(), key=lambda x: x[1])
    ''', 'max_pagerank_node')

    print(test)
    print(result)

    yield test == result, 1


# Aufgabe 2.6
@JPTest('Aufgabe 2.6', max_score=1, execute=[imports, load_graph, ('task-2-6',)])
def aufgabe2_6(tb: JPTestBook):
    result = tb.get('max_clique')

    tb.inject(load_graph)
    test = tb.inject('''
        max_clique = max(clique.find_cliques(G), key=len)
    ''', 'max_clique')

    yield test == result, 1


# Mapping
mapping = {
    "Diary of a Wimpy Kid: The Long Haul": "s468",
    "Ant-Man and the Wasp": "s433",
    "Descendants": "s820",
    "Camp Rock": "s772",
    "Brave Little Tailor": "s1432",
    "Phineas and Ferb: The Movie: Across the 2nd Dimension": "s1127",
    "Walt & El Grupo": "s507",
    "Becoming Cousteau": "s6",
    "Whispers: An Elephant's Tale": "s1404",
    "The Art of Skiing": "s1250",
    "Lost Temple of The Inca": "s457",
    "Meet the Deedles": "s1067",
    "The Santa Clause 3: The Escape Clause": "s1333",
    "Miracle at Midnight": "s1085",
    "I'll Be Home for Christmas": "s958",
    "Disney Channel Halloween House Party": "s377",
    "Flicka": "s173",
    "The Princess Diaries": "s1323",
    "Prep & Landing: Naughty vs. Nice": "s376",
    "Garfield": "s145",
    "Noelle": "s1106",
    "Pollyanna": "s1144",
    "Melody Time": "s1069",
    "Under the Helmet: The Legacy of Boba Fett": "s41",
    "Motocrossed": "s1093",
    "Miracle in Lane 2": "s1086",
    "Sea Scouts": "s588",
    "Bambi II": "s740",
    "Three Little Pigs": "s1363",
    "The Peanuts Movie": "s445",
    "Ernest Saves Christmas": "s2",
    "Tinker Bell and the Great Fairy Rescue": "s1373",
    "Recess: School's Out": "s1157",
    "Pirates of the Caribbean: At World's End": "s1132",
    "Hunt for the Abominable Snowman": "s454",
    "Mickey's Delayed Date": "s1076",
    "Rookie of the Year": "s57",
    "Dumbo": "s871",
    "Zenon: The Zequel": "s1427",
    "Bizarre Dinosaurs": "s753",
    "Herbie Rides Again": "s939",
    "Rescue Dog": "s1161",
    "Pluto's Sweater": "s1141",
    "Forky Asks a Question: What Is a Friend?": "s707",
    "Sleeping Beauty": "s1197",
    "Ice Age: Dawn of the Dinosaurs": "s1445",
    "Saludos Amigos": "s1175",
    "Wings of Life": "s861",
    "Miracle": "s1084",
    "Mickey's Twice Upon a Christmas": "s1080",
    "Robin Hood": "s1169",
    "Treasure Planet": "s1388",
    "Now You See It": "s1107",
    "Treasure of Matecumbe": "s1387",
    "Phineas and Ferb: The Movie: Candace Against the Universe": "s422",
    "Jungle Cat": "s986",
    "Thumbelina": "s58",
    "Smoky Mountain Park Rangers": "s106",
    "The Great Muppet Caper": "s1283",
    "Lost Cities: The Great Flood": "s61",
    "Incredible! The Story of Dr. Pol": "s693",
    "The Apple Dumpling Gang Rides Again": "s1248",
    "Hawaiian Vacation": "s1381",
    "Ice Age: Collision Course": "s483",
    "How to Play Football": "s580",
    "Zootopia": "s1429",
    "The Strongest Man in the World": "s1342",
    "Bedknobs and Broomsticks": "s1430",
    "Mrs. Doubtfire": "s141",
    "Babes in Toyland": "s738",
    "Bend It Like Beckham": "s1449",
    "Flora & Ulysses": "s298",
    "On Ice": "s583",
    "The Muppet Movie": "s1310",
    "A Kid in King Arthur's Court": "s716",
    "Unidentified Flying Mater": "s655",
    "Jane Goodall: The Hope": "s557",
    "Lamp Life": "s631",
    "Lonesome Ghosts": "s1024",
    "The Little Mermaid II: Return to the Sea": "s1299",
    "Ferdinand": "s318",
    "The Plausible Impossible": "s1319",
    "Jane": "s975",
    "The Love Bug": "s1305",
    "Star Wars: Episode I - The Phantom Menace": "s1219",
    "The Million Dollar Duck": "s1307",
    "Saving Mr. Banks": "s1180",
    "Spinning": "s652",
    "Halloweentown": "s927",
    "Bolt": "s756",
    "That Darn Cat": "s1238",
    "Mary Poppins": "s1065",
    "The Shaggy Dog": "s1337",
    "Tarzan & Jane": "s1233",
    "Ice Age: A Mammoth Christmas": "s3",
    "The Nutcracker and the Four Realms": "s351",
    "Sultan And The Rock Star": "s1226",
    "Dragon Around": "s576",
    "The Christmas Star": "s1267",
    "Thor: The Dark World": "s1053",
    "Forky Asks a Question: What Is Money?": "s898",
    "Clock Cleaners": "s796",
    "Recess: All Growed Down": "s1156",
    "Tiger Cruise": "s1368",
    "Pixel Perfect": "s1136",
    "Snowglobe": "s1202",
    "Mickey Mouse": "s1071",
    "X-Men: Days of Future Past": "s478",
    "The Three Musketeers": "s1349",
    "America's Greatest Animals": "s509",
    "Don't Look Under the Bed": "s863",
    "The Living Desert": "s1302",
    "The Cheetah Girls": "s1264",
    "Stitch! The Movie": "s1223",
    "The Parent Trap": "s1317",
    "Flowers and Trees": "s894",
    "Twitches Too": "s1396",
    "The Undefeated Presents: Hamilton In-Depth": "s479",
    "Winnie the Pooh": "s1409",
    "In the Footsteps of Elephant": "s581",
    "High School Musical 3: Senior Year": "s943",
    "We Bought a Zoo": "s169",
    "Star Wars: Episode II - Attack of the Clones": "s1213",
    "The Pre-Opening Report from Disneyland": "s467",
    "12 Dates of Christmas": "s712",
    "Canine Caddy": "s776",
    "Water Birds": "s551",
    "The Disney Holiday Singalong": "s350",
    "Coco": "s701",
    "Prom": "s596",
    "Shark Vs. Whale": "s155",
    "Cars": "s777",
    "Marvel One-Shot: All Hail the King": "s124",
    "Stargirl": "s606",
    "Tangled Ever After": "s34",
    "Adventure Thru the Walt Disney Archives": "s11",
    "Moana": "s1089",
    "Back to the Titanic": "s423",
    "The Real Right Stuff": "s362",
    "Secrets Of Christ's Tomb": "s1185",
    "Toy Story": "s1378",
    "Life Is Ruff": "s1017",
    "Avatar": "s736",
    "Aladdin": "s645",
    "Newsies": "s1105",
    "The Black Hole": "s1258",
    "Disney Holiday Magic Quest": "s340",
    "The Wild": "s1356",
    "National Treasure: Book of Secrets": "s1103",
    "The Poof Point": "s1320",
    "Return from Witch Mountain": "s1162",
    "Rip Girls": "s1168",
    "Inside Out": "s962",
    "Beverly Hills Chihuahua": "s387",
    "The Mistle-Tones": "s1308",
    "The Sorcerer's Apprentice": "s379",
    "High School Musical: The Musical: The Series: The Special": "s679",
    "The New Neighbor": "s591",
    "Cheaper by the Dozen 2": "s297",
    "Hatching Pete": "s934",
    "Girl vs. Monster": "s826",
    "Diary of a Wimpy Kid: Rodrick Rules": "s481",
    "Solo: A Star Wars Story": "s477",
    "The Lion King 1\u00bd": "s1296",
    "The Black Cauldron": "s1257",
    "The Chronicles of Narnia: Prince Caspian": "s1268",
    "Cars 3": "s779",
    "Big Business": "s630",
    "Bearly Asleep": "s743",
    "One Day at Disney": "s688",
    "The Lost Tomb of Alexander the Great": "s1304",
    "LEGO Star Wars Holiday Special": "s364",
    "White Fang 2: Myth of the White Wolf": "s251",
    "Alvin and the Chipmunks": "s81",
    "Life with Mikey": "s1018",
    "The Wizards Return: Alex vs. Alex": "s1358",
    "Ewoks: The Battle for Endor": "s259",
    "Expedition Everest": "s306",
    "Marvel Rising: Secret Warriors": "s1035",
    "The Thirteenth Year": "s1347",
    "Born Wild: The Next Generation": "s553",
    "The Emperor's New Groove": "s1273",
    "India's Wild Leopards": "s430",
    "Marvel's Behind the Mask": "s302",
    "Jade Eyed Leopard": "s104",
    "Heavyweights": "s936",
    "Adventures in Babysitting": "s188",
    "Mr. Duck Steps Out": "s1095",
    "Diary of a Wimpy Kid": "s813",
    "Ice Age: The Great Egg-Scapade": "s959",
    "The Cat from Outer Space": "s1436",
    "Soul": "s330",
    "Pluto and the Gopher": "s1138",
    "Man in Space": "s490",
    "X2": "s397",
    "The Old Mill": "s1314",
    "Life-Size 2": "s1019",
    "White Fang": "s1405",
    "Mike's New Car": "s1082",
    "A Spark Story": "s94",
    "The Goddess of Spring": "s1280",
    "Under Wraps": "s73",
    "The Absent-Minded Professor": "s1240",
    "X-Men: First Class": "s51",
    "Beverly Hills Chihuahua 2": "s138",
    "Wizards of Waverly Place: The Movie": "s1414",
    "Mr. Magoo": "s374",
    "Shark Beach With Chris Hemsworth": "s177",
    "Frankenweenie": "s594",
    "Winged Seduction: Birds of Paradise": "s1408",
    "Inspector Gadget 2": "s964",
    "Early to Bed": "s872",
    "Auntie Edna": "s735",
    "Waking Sleeping Beauty": "s1401",
    "Drain Alcatraz": "s658",
    "Hamilton": "s482",
    "Fantastic Mr. Fox": "s523",
    "Cheaper by the Dozen": "s296",
    "A Knight for a Day": "s717",
    "Tomorrowland": "s1443",
    "The Sandlot 2": "s187",
    "Tuck Everlasting": "s1392",
    "X-Men Origins: Wolverine": "s1446",
    "The Flood": "s1275",
    "Old Yeller": "s1109",
    "Super Rhino": "s671",
    "Teen Beach Movie": "s1236",
    "The Hockey Champ": "s1286",
    "Mr. Holland's Opus": "s398",
    "Apollo: Missions to the Moon": "s731",
    "Queen of Katwe": "s1151",
    "Secret of the Wings": "s1183",
    "Camp Rock 2: The Final Jam": "s773",
    "Float": "s893",
    "Garfield: A Tail of Two Kitties": "s284",
    "Cool Runnings": "s657",
    "Avengers: Infinity War": "s492",
    "Tarzan II": "s494",
    "The Brave Little Toaster Goes to Mars": "s1262",
    "The Happiest Millionaire": "s199",
    "Cloud 9": "s797",
    "Iron Man": "s1048",
    "Babes in the Woods": "s737",
    "Disneyland Around the Seasons": "s854",
    "College Road Trip": "s798",
    "The Fox and the Hound 2": "s1277",
    "Pinocchio": "s1130",
    "The Ugly Dachshund": "s1352",
    "Epic Holiday Showdown": "s339",
    "Black Beauty": "s353",
    "Let It Shine": "s1016",
    "Forky Asks a Question: What Is Love?": "s684",
    "The Story of the Faithful Wookiee": "s267",
    "The Jungle Book": "s499",
    "Skyrunners": "s1196",
    "Treasure Buddies": "s250",
    "Bedtime Stories": "s609",
    "Fuzzbucket": "s907",
    "The Fault in Our Stars": "s96",
    "Secrets of the King Cobra": "s1187",
    "Get a Clue": "s913",
    "D2: The Mighty Ducks": "s417",
    "The Computer Wore Tennis Shoes": "s1271",
    "Z-O-M-B-I-E-S": "s1424",
    "Roving Mars": "s1172",
    "Captain America: The First Avenger": "s1042",
    "LEGO Star Wars Terrifying Tales": "s83",
    "How to Swim": "s956",
    "X-Men: The Last Stand": "s226",
    "Titanic: 20 Years Later with James Cameron": "s1375",
    "Tugboat Mickey": "s1393",
    "The Pied Piper": "s1318",
    "Cheetah": "s788",
    "Fantastic Four": "s131",
    "Who Framed Roger Rabbit": "s1406",
    "The Tortoise and the Hare": "s1351",
    "Frozen": "s904",
    "Frank and Ollie": "s899",
    "Return to Oz": "s1164",
    "Red Tails": "s206",
    "Meet the Robinsons": "s1068",
    "The Queen Family Singalong": "s4",
    "Dark Phoenix": "s118",
    "22 vs. Earth": "s236",
    "Moon Mater": "s650",
    "That Darn Cat!": "s1239",
    "Forky Asks a Question: What Is a Pet?": "s675",
    "An Extremely Goofy Movie": "s728",
    "Teen Beach 2": "s1235",
    "The Hidden Kingdoms of China": "s444",
    "Mom's Got a Date with a Vampire": "s1090",
    "The Adventures of Huck Finn": "s1243",
    "The Kid": "s852",
    "Chip 'n Dale: Rescue Rangers": "s791",
    "Homeward Bound: The Incredible Journey": "s540",
    "Teen Spirit": "s1237",
    "Okavango: River of Dreams": "s292",
    "Three Blind Mouseketeers": "s1361",
    "The Mouseketeers at Walt Disney World": "s472",
    "Zenon: Z3": "s1428",
    "Fun and Fancy Free": "s906",
    "Magician Mickey": "s1029",
    "How to Fish": "s955",
    "A Goofy Movie": "s715",
    "Dadnapped": "s804",
    "Togo": "s681",
    "Food for Feudin'": "s896",
    "Cars 2": "s778",
    "Genius": "s910",
    "Donald's Tire Trouble": "s865",
    "The Avengers": "s1051",
    "Doug's 1st Movie": "s867",
    "Descendants: The Royal Wedding": "s101",
    "Wild Hearts Can't Be Broken": "s230",
    "La Luna": "s997",
    "Return of the Jedi": "s1215",
    "Iron Man & Captain America: Heroes United": "s390",
    "The Kid Who Would Be King": "s249",
    "Baby's Day Out": "s241",
    "Frenemies": "s903",
    "The Olympic Elk": "s555",
    "Hawaiian Holiday": "s935",
    "Incredibles 2": "s455",
    "Steamboat Willie": "s1221",
    "Tangled": "s1231",
    "Alice Through the Looking Glass": "s421",
    "The Adventures of Ichabod and Mr. Toad": "s1244",
    "Mulan II": "s1097",
    "Wind": "s683",
    "The Simple Things": "s1339",
    "The Hunchback of Notre Dame": "s1287",
    "WALL\u00b7E": "s1402",
    "Wendy Wu: Homecoming Warrior": "s1403",
    "Fantasia": "s884",
    "Purl": "s1149",
    "Ant-Man": "s1056",
    "Jack-Jack Attack": "s973",
    "Don's Fountain of Youth": "s573",
    "The Rescuers": "s1328",
    "Anastasia": "s345",
    "Pluto's Surprise Package": "s1140",
    "Pluto's Christmas Tree": "s1139",
    "Gnomeo & Juliet": "s273",
    "The Santa Clause 2": "s1332",
    "Guardians of the Galaxy": "s1046",
    "The Adventures of Greyfriars Bobby": "s925",
    "Out": "s526",
    "Annie": "s730",
    "Mater the Greater": "s784",
    "Flubber": "s895",
    "Trailer Horn": "s1385",
    "Get a Horse!": "s23",
    "Marvel Rising: Chasing Ghosts": "s694",
    "D3: The Mighty Ducks": "s418",
    "Third Man on the Mountain": "s271",
    "Beauty and the Beast: The Enchanted Christmas": "s745",
    "Quints": "s1152",
    "Frozen II": "s605",
    "The Sandlot: Heading Home": "s608",
    "Pirates of the Caribbean: The Curse of the Black Pearl": "s1134",
    "Trail Mix-Up": "s501",
    "Beverly Hills Chihuahua 3: Viva la Fiesta!": "s139",
    "Remember the Titans": "s1160",
    "Right on Track": "s1166",
    "Tinker Bell": "s1372",
    "The Hunchback of Notre Dame II": "s1288",
    "Christopher Robin": "s416",
    "Up": "s1398",
    "The Empire Strikes Back": "s1217",
    "Pocahontas II: Journey to a New World": "s1143",
    "Safety": "s344",
    "Ralph Breaks the Internet": "s343",
    "Loop": "s643",
    "Pluto's Purchase": "s561",
    "Double Teamed": "s866",
    "Howard": "s441",
    "Your Friend the Rat": "s1423",
    "Fantasia 2000": "s885",
    "Captain America: Civil War": "s1041",
    "Geek Charming": "s909",
    "The Boys: The Sherman Brothers' Story": "s528",
    "Wreck-It Ralph": "s1417",
    "Hidden Figures": "s400",
    "Iron Man 2": "s1049",
    "The Simpsons in Plusaversary": "s39",
    "Mickey's Once Upon a Christmas": "s1077",
    "Oceans": "s399",
    "Unidentified Flying Oddball": "s1397",
    "Descendants 3": "s628",
    "Muppets Most Wanted": "s1100",
    "Bone Bandit": "s757",
    "One Magic Christmas": "s1112",
    "The Sword in the Stone": "s1438",
    "The Journey of Natty Gann": "s1292",
    "Growing Fangs": "s212",
    "Into the Woods": "s335",
    "The Simpsons Movie": "s1193",
    "The Return of Jafar": "s721",
    "Cesar Millan: The Real Story": "s252",
    "Avengers: Endgame": "s1040",
    "Jack": "s972",
    "First Kid": "s891",
    "Jump In!": "s983",
    "Snow White and the Seven Dwarfs": "s1200",
    "Heavy Metal Mater": "s781",
    "Can of Worms": "s774",
    "Captain Marvel": "s1044",
    "Finding Dory": "s889",
    "Marvel Studios: Expanding the Universe": "s1037",
    "Happier Than Ever: A Love Letter to Los Angeles": "s117",
    "Party Central": "s1119",
    "The Ultimate Christmas Present": "s1354",
    "Muppets Haunted Mansion": "s71",
    "Tinker Bell and the Lost Treasure": "s1374",
    "Tarzan": "s493",
    "All in a Nutshell": "s569",
    "The Tigger Movie": "s1350",
    "The Making of Happier Than Ever: A Love Letter to Los Angeles": "s37",
    "Walking with Dinosaurs": "s157",
    "Once Upon a Snowman": "s384",
    "Three Men and a Baby": "s1365",
    "Monsters University": "s1091",
    "Journey to the Center of the Earth": "s982",
    "Spooky Buddies": "s95",
    "Bugged": "s656",
    "Donald's Golf Game": "s864",
    "Big Hero 6": "s751",
    "Tall Tale": "s1230",
    "Home Alone": "s365",
    "Trick or Treat": "s420",
    "Bride of Boogedy": "s535",
    "The Wise Little Hen": "s1357",
    "High School Musical: The Musical: The Holiday Special": "s342",
    "Geri's Game": "s912",
    "Eddie the Eagle": "s1448",
    "The Proud Family Movie": "s1325",
    "Ye Olden Days": "s1419",
    "Peter Pan": "s1122",
    "Bears": "s856",
    "Return to Never Land": "s1123",
    "Phineas and Ferb: Mission Marvel": "s1128",
    "Chicken Little": "s790",
    "The Incredibles": "s1291",
    "Ice Princess": "s960",
    "The Pacifier": "s200",
    "The Golden Touch": "s1281",
    "The Rookie": "s1330",
    "Jungle Cruise": "s25",
    "Thor": "s1052",
    "Ice Age: The Meltdown": "s152",
    "Blank Check": "s754",
    "Tron": "s1390",
    "Time Travel Mater": "s653",
    "Dug's Special Mission": "s870",
    "The Sandlot": "s186",
    "Going to the Mat": "s917",
    "Read It and Weep": "s1154",
    "Forky Asks a Question: What Is Time?": "s702",
    "Ruby Bridges": "s1173",
    "Stuntman": "s156",
    "Monkey Kingdom": "s860",
    "Winnie the Pooh: A Very Merry Pooh Year": "s1410",
    "Mickey Down Under": "s1070",
    "The Biscuit Eater": "s1256",
    "Star Wars: The Force Awakens": "s1218",
    "Jingle All the Way": "s44",
    "Super Buddies": "s1227",
    "Donald's Dog Laundry": "s574",
    "The Mighty Ducks": "s486",
    "Lady and the Tramp II: Scamp's Adventure": "s1434",
    "Valiant": "s1400",
    "The Most Magical Story on Earth: 50 Years of Walt Disney World": "s72",
    "G-Force": "s604",
    "Disney Princess Remixed: An Ultimate Princess Celebration": "s123",
    "Planes: Fire & Rescue": "s361",
    "Chimpanzee": "s858",
    "Black Panther": "s610",
    "MARS: Inside SpaceX": "s1032",
    "Mickey's Christmas Carol": "s1075",
    "The Olympic Champ": "s1315",
    "Mickey's Trailer": "s1079",
    "Grand Canyonscope": "s922",
    "High School Musical": "s941",
    "101 Dalmatians II: Patch's London Adventure": "s710",
    "Forky Asks a Question: What Is a Leader?": "s677",
    "The Book of Life": "s299",
    "Mater and the Ghostlight": "s1066",
    "The Legend of Mor'du": "s1295",
    "Toy Story That Time Forgot": "s320",
    "Once Upon A Mattress": "s1111",
    "Eddie's Million Dollar Cook Off": "s875",
    "Cow Belles": "s802",
    "Marvel Studios: Assembling a Universe": "s1036",
    "The Even Stevens Movie": "s1274",
    "Sister Act": "s1194",
    "The Luck of the Irish": "s1027",
    "Iron Man 3": "s1050",
    "Jumping Ship": "s984",
    "Small Fry": "s1383",
    "Kronk's New Groove": "s996",
    "Mark Twain and Me": "s256",
    "Those Calloways": "s1439",
    "George of the Jungle 2": "s678",
    "Boundin'": "s759",
    "Percy Jackson & the Olympians: The Lightning Thief": "s513",
    "Chef Donald": "s789",
    "Avalon High": "s816",
    "Belle's Magical World": "s744",
    "Lost Cities: Megacity of the Maya Warrior King": "s62",
    "Night at the Museum: Battle of the Smithsonian": "s1447",
    "Because of Winn-Dixie": "s621",
    "Maleficent": "s84",
    "The Small One": "s592",
    "Miraculous World: Shanghai \u2013 The Legend of Ladydragon": "s174",
    "Santa Paws 2: The Santa Pups": "s1178",
    "The Band Concert": "s1253",
    "Fantastic Four: Rise of the Silver Surfer": "s228",
    "LEGO Frozen Northern Lights": "s1001",
    "Earth Live": "s873",
    "Dolphin Reef": "s572",
    "Shark vs. Surfer": "s154",
    "Alvin and the Chipmunks: Chipwrecked": "s43",
    "Wild Portugal": "s396",
    "Oklahoma!": "s240",
    "Secrets of Life": "s1186",
    "A Bug's Life": "s714",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader": "s394",
    "Herbie Goes to Monte Carlo": "s938",
    "Aladdin and the King of Thieves": "s720",
    "Muppet Treasure Island": "s1099",
    "The Shaggy D.A.": "s1336",
    "Race to Witch Mountain": "s484",
    "Sister Act 2: Back in the Habit": "s1195",
    "Mail Dog": "s1030",
    "Star Wars: Galaxy's Edge - Adventure Awaits": "s443",
    "Magic Camp": "s432",
    "Go Figure": "s916",
    "Raya and the Last Dragon": "s205",
    "Lemonade Mouth": "s1013",
    "Halloweentown II: Kalabar's Revenge": "s929",
    "The Suite Life Movie": "s1343",
    "Beaver Valley": "s542",
    "Home Sweet Home Alone": "s24",
    "The Big Year": "s269",
    "Doctor Strange": "s1045",
    "Olaf's Frozen Adventure": "s1108",
    "The Ballad of Nessie": "s35",
    "Snowball Express": "s1201",
    "Phineas and Ferb: Star Wars": "s612",
    "Let's Stick Together": "s560",
    "Forky Asks a Question: What Is Art?": "s704",
    "The Lion King II: Simba's Pride": "s1297",
    "Toy Story 2": "s1379",
    "Dinosaur": "s814",
    "Cruella": "s121",
    "Descendants 2": "s812",
    "The Odd Life of Timothy Green": "s598",
    "The Aristocats": "s1249",
    "Onward": "s584",
    "The Castaway Cowboy": "s1263",
    "You Again": "s304",
    "Empire of Dreams: The Story of the Star Wars Trilogy": "s879",
    "The African Lion": "s1246",
    "Stuck in the Suburbs": "s1225",
    "The Big Green": "s485",
    "Johnny Kapahala: Back on Board": "s978",
    "Home Alone 3": "s367",
    "Stepsister from Planet Weird": "s1222",
    "The Game Plan": "s1278",
    "Duck the Halls: A Mickey Mouse Christmas Special": "s1",
    "Disney's Broadway Hits at London's Royal Albert Hall": "s102",
    "Princess Protection Program": "s1148",
    "Benji the Hunted": "s748",
    "The One and Only Ivan": "s426",
    "Splash": "s624",
    "Beauty and the Beast": "s424",
    "Iron Will": "s971",
    "You Wish!": "s1422",
    "The Little Mermaid: Ariel's Beginning": "s1300",
    "Double Dribble": "s575",
    "Home on the Range": "s946",
    "Deep Blue": "s811",
    "Glory Road": "s691",
    "Out of Scale": "s585",
    "Smart House": "s1198",
    "Richie Rich's Christmas Wish": "s1165",
    "Tangled: Before Ever After": "s1232",
    "Iron Man & Hulk: Heroes United": "s620",
    "Marvel Rising: Playing with Fire": "s618",
    "Operation Dumbo Drop": "s1114",
    "A Ring of Endless Light": "s718",
    "Drain The Sunken Pirate City": "s662",
    "Space Buddies": "s49",
    "Home Alone 2: Lost in New York": "s366",
    "Starstruck": "s1220",
    "Star Wars: The Rise of Skywalker": "s531",
    "Star Wars: The Last Jedi": "s676",
    "El Materdor": "s649",
    "Monster Truck Mater": "s785",
    "Rio": "s248",
    "Underdog": "s125",
    "Minutemen": "s1083",
    "Lilo & Stitch 2: Stitch Has a Glitch": "s1022",
    "The Fox and the Hound": "s1276",
    "Guardians of the Galaxy Vol. 2": "s1047",
    "Pirates of the Caribbean: On Stranger Tides": "s111",
    "My Favorite Martian": "s1101",
    "The Lizzie McGuire Movie": "s1303",
    "Dan in Real Life": "s122",
    "Folklore: The Long Pond Studio Sessions": "s357",
    "Mickey's Rival": "s1078",
    "Marvel Studios' 2021 Disney+ Day Special": "s27",
    "Avengers: Age of Ultron": "s1039",
    "Darby O'Gill and the Little People": "s805",
    "Atlantis: Milo's Return": "s733",
    "My Dog the Thief": "s623",
    "Wild Uganda": "s312",
    "Maggie Simpson in Playdate with Destiny": "s565",
    "Secretariat": "s1184",
    "The Nightmare Before Christmas": "s1369",
    "Hiccups": "s782",
    "Lend a Paw": "s1014",
    "Under the Sea: A Descendants Story": "s841",
    "Marvel Rising: Operation Shuri": "s617",
    "Inner Workings": "s961",
    "Beach Picnic": "s742",
    "Luca": "s195",
    "Emil and the Detectives": "s878",
    "A Christmas Carol": "s371",
    "Pete's Dragon": "s1121",
    "Mulan": "s348",
    "The Princess and the Frog": "s1322",
    "Artemis Fowl": "s503",
    "Hocus Pocus": "s945",
    "Far Away From Raven's Home": "s110",
    "The Prince and the Pauper": "s1321",
    "BURN\u00b7E": "s769",
    "Timmy Failure: Mistakes Were Made": "s626",
    "The Straight Story": "s593",
    "Pixar 2021 Disney+ Day Special": "s31",
    "Black Widow": "s75",
    "Snow Buddies": "s48",
    "The Reluctant Dragon": "s1326",
    "Recess: Taking the Fifth Grade": "s1158",
    "Prep & Landing Stocking Stuffer: Operation: Secret Santa": "s46",
    "Justin Morgan Had a Horse": "s1433",
    "Around the World in 80 Days": "s629",
    "Shang-Chi and the Legend of the Ten Rings": "s32",
    "Chasing the Equinox": "s510",
    "Playing with Sharks": "s153",
    "Zapped": "s1425",
    "Black Is King": "s450",
    "Treasure Island": "s1386",
    "Tinker Bell and the Legend of the NeverBeast": "s221",
    "Ratatouille": "s1153",
    "3 Men and a Little Lady": "s1366",
    "Candleshoe": "s775",
    "While You Were Sleeping": "s487",
    "Jonas Brothers: The Concert Experience": "s980",
    "Star Wars: Episode III - Revenge of the Sith": "s1216",
    "Expedition Amelia": "s690",
    "The Good Dinosaur": "s1282",
    "Prep & Landing": "s375",
    "The Princess Bride": "s548",
    "Frozen Fever": "s22",
    "Forky Asks a Question: What Is Reading?": "s642",
    "The Sound of Music": "s1340",
    "Santa Buddies": "s47",
    "Tummy Trouble": "s502",
    "The Little Mermaid": "s1298",
    "The Search for Santa Paws": "s50",
    "Freaky Friday": "s901",
    "Santa's Workshop": "s1179",
    "Invisible Sister": "s968",
    "Tru Confessions": "s1391",
    "Piglet's Big Movie": "s1129",
    "Thor: Ragnarok": "s686",
    "You Lucky Dog": "s1421",
    "The Story of the Animated Drawing": "s506",
    "The Jungle Book: Mowgli's Story": "s1294",
    "Dinner Is Served": "s210",
    "Pirates of the Caribbean: Dead Man's Chest": "s1133",
    "Toy Story of Terror!": "s386",
    "The Liberty Story": "s505",
    "Lambert the Sheepish Lion": "s582",
    "Strange Magic": "s198",
    "Drain the Titanic": "s663",
    "Captain Sparky vs. The Flying Saucers": "s1450",
    "Toy Story 4": "s627",
    "The Little Mermaid Live!": "s703",
    "X-Men: Apocalypse": "s474",
    "Pooh's Grand Adventure: The Search for Christopher Robin": "s1145",
    "Hamilton: History Has Its Eyes On You": "s476",
    "Zenon: Girl of the 21st Century": "s1426",
    "Phantom of the Megaplex": "s1124",
    "Miss Peregrine's Home for Peculiar Children": "s282",
    "The Ugly Duckling": "s1353",
    "DuckTales: The Movie - Treasure of the Lost Lamp": "s869",
    "Hannah Montana: The Movie": "s933",
    "Den Brother": "s819",
    "Squanto: A Warrior's Tale": "s257",
    "Brother Bear 2": "s766",
    "Bad Hair Day": "s817",
    "The Little Whirlwind": "s1301",
    "Born in China": "s857",
    "Yellowstone Cubs": "s1420",
    "Mr. Mouse Takes a Trip": "s1096",
    "The Ghosts of Buxley Hall": "s1279",
    "Maleficent: Mistress of Evil": "s530",
    "Three Days": "s1362",
    "Riley's First Date?": "s1167",
    "Mary Poppins Returns": "s315",
    "Spin": "s33",
    "The Ewok Adventure": "s258",
    "High School Musical 2": "s942",
    "Ready to Run": "s1155",
    "X-Men": "s132",
    "Feast": "s21",
    "Lilo & Stitch": "s1021",
    "Oliver & Company": "s1110",
    "Tinker Bell and the Pirate Fairy": "s500",
    "Mickey's Tale of Two Witches": "s70",
    "George & A.J.": "s911",
    "The Three Caballeros": "s1348",
    "Brink!": "s764",
    "Winter Storage": "s1412",
    "Pooh's Heffalump Movie": "s1146",
    "Bob Ballard: An Explorer's Life": "s55",
    "Marvel Rising: Heart of Iron": "s695",
    "Night at the Museum": "s263",
    "The Color of Friendship": "s1270",
    "Pirates of the Caribbean: Dead Men Tell No Tales": "s462",
    "Jungle 2 Jungle": "s985",
    "Flight of the Navigator": "s892",
    "Forky Asks a Question: What Is a Computer?": "s682",
    "Hannah Montana & Miley Cyrus: Best of Both Worlds Concert": "s932",
    "Aquamarine": "s1444",
    "Eragon": "s129",
    "Marvel Rising: Battle of the Bands": "s668",
    "The Cheetah Girls: One World": "s1266",
    "Escape to Witch Mountain": "s881",
    "Buffalo Dreams": "s767",
    "Pocahontas": "s1142",
    "EverAfter": "s409",
    "Cinderella": "s793",
    "Captain America: The Winter Soldier": "s1043",
    "The Radiator Springs 500\u00bd": "s786",
    "Corn Chips": "s801",
    "Alvin and the Chipmunks: The Road Chip": "s82",
    "Myth: A Frozen Tale": "s291",
    "John Carter": "s532",
    "Kim Possible: So the Drama": "s990",
    "Brave": "s761",
    "Inspector Gadget": "s963",
    "Isle of Dogs": "s314",
    "The Finest Hours": "s607",
    "Clouds": "s388",
    "The Rescuers Down Under": "s1329",
    "How to Play Baseball": "s541",
    "Mighty Joe Young": "s1081",
    "The Grasshopper and the Ants": "s923",
    "A Muppets Christmas: Letters to Santa": "s10",
    "Johnny Tsunami": "s979",
    "Horse Sense": "s950",
    "Atlantis Rising": "s732",
    "George of the Jungle": "s538",
    "Finding Nemo": "s890",
    "The Sign of Zorro": "s1338",
    "Davy Crockett and the River Pirates": "s807",
    "The Many Adventures of Winnie the Pooh": "s1306",
    "James and the Giant Peach": "s974",
    "Swiss Family Robinson": "s1228",
    "Decorating Disney: Holiday Magic": "s810",
    "The Santa Clause": "s1331",
    "101 Dalmatians": "s709",
    "The Bears and I": "s1254",
    "Partly Cloudy": "s1118",
    "Camp Nowhere": "s771",
    "Bambi": "s739",
    "Amy": "s727",
    "The Adventures of Bullwhip Griffin": "s1242",
    "Lady and the Tramp": "s999",
    "Z-O-M-B-I-E-S 2": "s429",
    "Beezy Bear": "s746",
    "Kazaam": "s987",
    "Willow": "s42",
    "The Lost City Of Machu Picchu": "s470",
    "The Big Bad Wolf": "s1255",
    "Boat Builders": "s755",
    "The Boy Who Talked to Badgers": "s590",
    "The Country Bears": "s1272",
    "Mickey's Birthday Party": "s1074",
    "Partysaurus Rex": "s1382",
    "The Vanishing Prairie": "s1355",
    "Gotta Kick It Up!": "s921",
    "Enchanted": "s20",
    "Mater Private Eye": "s783",
    "Forky Asks a Question: What Is Cheese?": "s646",
    "Ciao Alberto": "s17",
    "Secret Society of Second Born Royals": "s402",
    "Sharpay's Fabulous Adventure": "s1190",
    "Tokyo Mater": "s654",
    "The Scream Team": "s1334",
    "Great Shark Chow Down": "s324",
    "Prince of Persia: The Sands of Time": "s442",
    "Cinderella III: A Twist in Time": "s795",
    "Aliens of the Deep": "s723",
    "Max Keeble's Big Move": "s329",
    "Paperman": "s30",
    "Homeward Bound II: Lost in San Francisco": "s539",
    "Man of the House": "s255",
    "Alice in Wonderland": "s722",
    "A Celebration of the Music from Coco": "s563",
    "The Muppets": "s1311",
    "Confessions of a Teenage Drama Queen": "s799",
    "Ferdinand the Bull": "s888",
    "Chip an' Dale": "s792",
    "The Greatest Game Ever Played": "s1284",
    "Thru the Mirror": "s1367",
    "Tom and Huck": "s1377",
    "The Swap": "s1346",
    "Winnie the Pooh: Springtime with Roo": "s1411",
    "The Great Mouse Detective": "s1437",
    "Leroy & Stitch": "s1015",
    "Sharks of the Bermuda Triangle": "s265",
    "Teacher's Pet": "s1234",
    "National Treasure": "s552",
    "The Moon-Spinners": "s521",
    "The Lion King": "s632",
    "Toby Tortoise Returns": "s1376",
    "Hounded": "s952",
    "Halloweentown High": "s928",
    "Cadet Kelly": "s770",
    "Big Sur-Wild California": "s496",
    "Nature's Half Acre": "s545",
    "Three Little Wolves": "s1364",
    "Planes": "s360",
    "Toy Story 3": "s1380",
    "The Scariest Story Ever: A Mickey Mouse Halloween Spooktacular": "s85",
    "Confessions of a Shopaholic": "s100",
    "Hercules": "s940",
    "Rogue One: A Star Wars Story": "s1171",
    "Sacred Planet": "s1174",
    "Paris to Pittsburgh": "s1117",
    "The Greatest Showman": "s438",
    "Perri": "s1120",
    "Society Dog Show": "s1204",
    "Brother Bear": "s765",
    "Before the Flood": "s747",
    "Herbie Goes Bananas": "s937",
    "Rescue Squad Mater": "s651",
    "The Last Song": "s597",
    "Atlantis: The Lost Empire": "s734",
    "The Cheetah Girls 2": "s1265",
    "The Muppet Christmas Carol": "s1309",
    "The Princess Diaries 2: Royal Engagement": "s1324",
    "102 Dalmatians": "s711",
    "The Island at the Top of the World": "s261",
    "Full-Court Miracle": "s905",
    "How to Build a Better Boy": "s954",
    "Upside-Down Magic": "s307",
    "Jingle All the Way 2": "s45",
    "Sky High": "s349",
    "Gus": "s926",
    "Mars: One Day on the Red Planet": "s425",
    "Air Mater": "s780",
    "Mr. Boogedy": "s1094",
    "African Cats": "s855",
    "The Incredible Journey": "s1290",
    "Blackbeard's Ghost": "s1431",
    "Holes": "s666",
    "10 Things I Hate About You": "s708",
    "Mickey and the Seal": "s519",
    "Mars Needs Moms": "s595",
    "Return to Halloweentown": "s1163",
    "Pluto's Party": "s587",
    "Invincible": "s967",
    "Twitches": "s1395",
    "The Apple Dumpling Gang": "s1247",
    "Elmer Elephant": "s578",
    "A Wrinkle in Time": "s600",
    "Godmothered": "s346",
    "Eight Below": "s876",
    "Alley Cats Strike": "s724",
    "The Jungle Book 2": "s1293",
    "The Haunted Mansion": "s1285",
    "Kim Possible": "s989",
    "Sharkcano": "s168",
    "The Brave Little Toaster to the Rescue": "s762",
    "Cinderella II: Dreams Come True": "s794"
}
